spring:
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /api

jwt.secret: ${SEC_SECRET}
server:
  servlet:
    context-path: /api